// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertClickDaily = `-- name: UpsertClickDaily :exec
INSERT INTO clicks_daily (link_id, day, count)
VALUES ($1, CURRENT_DATE, 1)
ON CONFLICT (link_id, day) DO UPDATE SET count = clicks_daily.count + 1
`

func (q *Queries) UpsertClickDaily(ctx context.Context, linkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertClickDaily, linkID)
	return err
}

const getClickStats = `-- name: GetClickStats :many
SELECT day, count
FROM clicks_daily
WHERE link_id = $1
  AND day >= CURRENT_DATE - $2::int
ORDER BY day ASC
`

type GetClickStatsParams struct {
	LinkID   pgtype.UUID `json:"link_id"`
	DaysBack int32       `json:"days_back"`
}

type GetClickStatsRow struct {
	Day   time.Time `json:"day"`
	Count int32     `json:"count"`
}

func (q *Queries) GetClickStats(ctx context.Context, arg GetClickStatsParams) ([]GetClickStatsRow, error) {
	rows, err := q.db.Query(ctx, getClickStats, arg.LinkID, arg.DaysBack)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClickStatsRow{}
	for rows.Next() {
		var i GetClickStatsRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalClicks = `-- name: GetTotalClicks :one
SELECT COALESCE(SUM(count), 0)::bigint AS total
FROM clicks_daily
WHERE link_id = $1
`

func (q *Queries) GetTotalClicks(ctx context.Context, linkID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalClicks, linkID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getTotalClicksByUser = `-- name: GetTotalClicksByUser :many
SELECT cd.link_id, COALESCE(SUM(cd.count), 0)::bigint AS total
FROM clicks_daily cd
JOIN links l ON l.id = cd.link_id
WHERE l.user_id = $1 AND l.deleted_at IS NULL
GROUP BY cd.link_id
`

type GetTotalClicksByUserRow struct {
	LinkID pgtype.UUID `json:"link_id"`
	Total  int64       `json:"total"`
}

func (q *Queries) GetTotalClicksByUser(ctx context.Context, userID pgtype.UUID) ([]GetTotalClicksByUserRow, error) {
	rows, err := q.db.Query(ctx, getTotalClicksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTotalClicksByUserRow{}
	for rows.Next() {
		var i GetTotalClicksByUserRow
		if err := rows.Scan(&i.LinkID, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
