// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (user_id, slug, original_url, is_custom, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, slug, original_url, is_custom, expires_at, created_at, updated_at
`

type CreateLinkParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Slug        string             `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	IsCustom    bool               `json:"is_custom"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateLinkRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Slug        string             `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	IsCustom    bool               `json:"is_custom"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.Slug,
		arg.OriginalUrl,
		arg.IsCustom,
		arg.ExpiresAt,
	)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.OriginalUrl,
		&i.IsCustom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkBySlug = `-- name: GetLinkBySlug :one
SELECT id, user_id, slug, original_url, is_custom, expires_at, created_at, updated_at
FROM links
WHERE slug = $1 AND deleted_at IS NULL
`

type GetLinkBySlugRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Slug        string             `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	IsCustom    bool               `json:"is_custom"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Active (non-deleted) link by slug. Used by the redirect hot path.
func (q *Queries) GetLinkBySlug(ctx context.Context, slug string) (GetLinkBySlugRow, error) {
	row := q.db.QueryRow(ctx, getLinkBySlug, slug)
	var i GetLinkBySlugRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.OriginalUrl,
		&i.IsCustom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinksByUserID = `-- name: GetLinksByUserID :many
SELECT id, user_id, slug, original_url, is_custom, expires_at, created_at, updated_at
FROM links
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetLinksByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetLinksByUserIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Slug        string             `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	IsCustom    bool               `json:"is_custom"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Paginated list of a user's active links, newest first.
func (q *Queries) GetLinksByUserID(ctx context.Context, arg GetLinksByUserIDParams) ([]GetLinksByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getLinksByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLinksByUserIDRow{}
	for rows.Next() {
		var i GetLinksByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.OriginalUrl,
			&i.IsCustom,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLink = `-- name: SoftDeleteLink :exec
UPDATE links
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteLink, id)
	return err
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET original_url = COALESCE($1, original_url),
    slug         = COALESCE($2, slug),
    expires_at   = $3,
    updated_at   = NOW()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, user_id, slug, original_url, is_custom, expires_at, created_at, updated_at
`

type UpdateLinkParams struct {
	OriginalUrl pgtype.Text        `json:"original_url"`
	Slug        pgtype.Text        `json:"slug"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ID          pgtype.UUID        `json:"id"`
}

type UpdateLinkRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Slug        string             `json:"slug"`
	OriginalUrl string             `json:"original_url"`
	IsCustom    bool               `json:"is_custom"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Updates mutable fields of an active link. NULL arguments leave a field unchanged
// (handled via COALESCE) except expires_at, which is set verbatim so it can be cleared.
func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.OriginalUrl,
		arg.Slug,
		arg.ExpiresAt,
		arg.ID,
	)
	var i UpdateLinkRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.OriginalUrl,
		&i.IsCustom,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
