// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Total active links for a user, honoring the same optional search filter as the
	// list query so pagination totals stay consistent.
	CountLinksByUserID(ctx context.Context, arg CountLinksByUserIDParams) (int64, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error)
	// Stores a refresh token by its SHA-256 hash (never the plaintext token).
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// Inserts a new user. The caller hashes the password before calling.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Housekeeping: removes tokens past their expiry. Intended for a periodic job.
	DeleteExpiredTokens(ctx context.Context) error
	// Last N days of click data for a link, ordered chronologically.
	// Returns rows only for days with clicks; the caller fills zero-days.
	GetClickStats(ctx context.Context, arg GetClickStatsParams) ([]GetClickStatsRow, error)
	// Active (non-deleted) link by slug. Used by the redirect hot path.
	GetLinkBySlug(ctx context.Context, slug string) (GetLinkBySlugRow, error)
	// A user's single active link by slug. Used for detail, update, and delete so
	// ownership is enforced in the query itself.
	GetLinkBySlugAndUser(ctx context.Context, arg GetLinkBySlugAndUserParams) (GetLinkBySlugAndUserRow, error)
	// Paginated list of a user's active links. An optional case-insensitive search
	// (sqlc.narg('search')) filters by slug or destination URL. Sorting is driven by
	// two boolean flags so the four (column × direction) combinations resolve in SQL
	// without dynamic string building: sort_expires picks expires_at over created_at,
	// and sort_asc picks ascending over descending.
	GetLinksByUserID(ctx context.Context, arg GetLinksByUserIDParams) ([]GetLinksByUserIDRow, error)
	// Looks up a refresh token by its hash. The caller checks expiry and revocation.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	// Lifetime click count for a single link.
	GetTotalClicks(ctx context.Context, linkID pgtype.UUID) (int64, error)
	// Total clicks per link for a user's links. Used to populate click_count
	// in the dashboard list without N+1 queries.
	GetTotalClicksByUser(ctx context.Context, userID pgtype.UUID) ([]GetTotalClicksByUserRow, error)
	// Fetches a user (including password_hash) by email for login.
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Fetches a user by id. Used after refresh-token validation to issue a new
	// access token with the current role.
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// Marks a refresh token revoked (idempotent: only sets revoked_at if still active).
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	// Reports whether an active link already uses this slug. Used by slug generation
	// (collision retry) and custom-alias validation.
	SlugExists(ctx context.Context, slug string) (bool, error)
	SoftDeleteLink(ctx context.Context, id pgtype.UUID) error
	// Updates mutable fields of an active link. NULL arguments leave a field unchanged
	// (handled via COALESCE) except expires_at, which is set verbatim so it can be cleared.
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error)
	// Idempotent daily click increment. Called async on each redirect.
	// Bucketed by UTC calendar day (not the session/server timezone) so it always
	// agrees with the Go-side UTC day math in fillZeroDays.
	UpsertClickDaily(ctx context.Context, linkID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
