// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error)
	// Active (non-deleted) link by slug. Used by the redirect hot path.
	GetLinkBySlug(ctx context.Context, slug string) (GetLinkBySlugRow, error)
	// Paginated list of a user's active links, newest first.
	GetLinksByUserID(ctx context.Context, arg GetLinksByUserIDParams) ([]GetLinksByUserIDRow, error)
	SoftDeleteLink(ctx context.Context, id pgtype.UUID) error
	// Updates mutable fields of an active link. NULL arguments leave a field unchanged
	// (handled via COALESCE) except expires_at, which is set verbatim so it can be cleared.
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error)
}

var _ Querier = (*Queries)(nil)
